name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:  
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd .\form-system\front\ ; yarn 
    - run: cd .\form-system\front\ ; yarn build
    - run: cd .\form-system\front\ ; yarn test
    - run: cd .\form-system\front\ ; yarn lint
    - run: cd .\form-system\front\ ; yarn build-storybook
    - run: cd .\form-system\front\ ; yarn add chromatic
    - run: cd .\form-system\front\ ; npx chromatic
   
