name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
      env:  
        PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
    - run: cd .\form-system\front\ ; yarn 
    - run: cd .\form-system\front\ ; yarn build
    - run: cd .\form-system\front\ ; yarn test
    - run: cd .\form-system\front\ ; yarn lint
    - run: cd .\form-system\front\ ; yarn build-storybook
    - run: cd .\form-system\front\ ; chromatic --project-token="$env:PROJECT_TOKEN"
   
